### ISSUE TITLE
Note font color on Elementary OS cannot be set to black

### ISSUE THREAD

**Issue by envieme** [UbuntuBudgie/desktopfolder#10]
On Elementary OS Juno, new notes text color cannot be set. It is always light gray. Other things like header text color, background color, background paper texture all can be set. 

![Screenshot from 2019-06-03 11-15-57](https://user-images.githubusercontent.com/1422393/58773799-0e988580-85f1-11e9-84d3-39a681277731.png)

**Comment by fossfreedom** [comment]
Please report this upstream https://github.com/spheras/desktopfolder
